name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - run: pip install black codespell isort pytest #flake8 
=======
      - run: pip install black codespell isort pytest # flake8

      - run: black --check . || true
      # - run: black --diff . || true
      # - if: matrix.python-version >= 3.6
      #  run: |
      #    pip install black
      #    black --check . || true
      - run: codespell --quiet-level=2 || true  # --ignore-words-list="" --skip=""

      - run: isort --profile black . || true
      - run: pip install -r requirements.txt || true
      - run: pytest . || true
